/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as InstellingenRouteImport } from './routes/instellingen'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WardrobeIndexRouteImport } from './routes/wardrobe/index'
import { Route as OutfitsIndexRouteImport } from './routes/outfits/index'
import { Route as WardrobeToevoegenRouteImport } from './routes/wardrobe/toevoegen'
import { Route as OutfitsNieuwRouteImport } from './routes/outfits/nieuw'
import { Route as OutfitsOutfitsIdRouteImport } from './routes/outfits/$outfitsId'
import { Route as WardrobeItemItemIdRouteImport } from './routes/wardrobe/item.$itemId'

const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const InstellingenRoute = InstellingenRouteImport.update({
  id: '/instellingen',
  path: '/instellingen',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WardrobeIndexRoute = WardrobeIndexRouteImport.update({
  id: '/wardrobe/',
  path: '/wardrobe/',
  getParentRoute: () => rootRouteImport,
} as any)
const OutfitsIndexRoute = OutfitsIndexRouteImport.update({
  id: '/outfits/',
  path: '/outfits/',
  getParentRoute: () => rootRouteImport,
} as any)
const WardrobeToevoegenRoute = WardrobeToevoegenRouteImport.update({
  id: '/wardrobe/toevoegen',
  path: '/wardrobe/toevoegen',
  getParentRoute: () => rootRouteImport,
} as any)
const OutfitsNieuwRoute = OutfitsNieuwRouteImport.update({
  id: '/outfits/nieuw',
  path: '/outfits/nieuw',
  getParentRoute: () => rootRouteImport,
} as any)
const OutfitsOutfitsIdRoute = OutfitsOutfitsIdRouteImport.update({
  id: '/outfits/$outfitsId',
  path: '/outfits/$outfitsId',
  getParentRoute: () => rootRouteImport,
} as any)
const WardrobeItemItemIdRoute = WardrobeItemItemIdRouteImport.update({
  id: '/wardrobe/item/$itemId',
  path: '/wardrobe/item/$itemId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/instellingen': typeof InstellingenRoute
  '/wishlist': typeof WishlistRoute
  '/outfits/$outfitsId': typeof OutfitsOutfitsIdRoute
  '/outfits/nieuw': typeof OutfitsNieuwRoute
  '/wardrobe/toevoegen': typeof WardrobeToevoegenRoute
  '/outfits': typeof OutfitsIndexRoute
  '/wardrobe': typeof WardrobeIndexRoute
  '/wardrobe/item/$itemId': typeof WardrobeItemItemIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/instellingen': typeof InstellingenRoute
  '/wishlist': typeof WishlistRoute
  '/outfits/$outfitsId': typeof OutfitsOutfitsIdRoute
  '/outfits/nieuw': typeof OutfitsNieuwRoute
  '/wardrobe/toevoegen': typeof WardrobeToevoegenRoute
  '/outfits': typeof OutfitsIndexRoute
  '/wardrobe': typeof WardrobeIndexRoute
  '/wardrobe/item/$itemId': typeof WardrobeItemItemIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/instellingen': typeof InstellingenRoute
  '/wishlist': typeof WishlistRoute
  '/outfits/$outfitsId': typeof OutfitsOutfitsIdRoute
  '/outfits/nieuw': typeof OutfitsNieuwRoute
  '/wardrobe/toevoegen': typeof WardrobeToevoegenRoute
  '/outfits/': typeof OutfitsIndexRoute
  '/wardrobe/': typeof WardrobeIndexRoute
  '/wardrobe/item/$itemId': typeof WardrobeItemItemIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/instellingen'
    | '/wishlist'
    | '/outfits/$outfitsId'
    | '/outfits/nieuw'
    | '/wardrobe/toevoegen'
    | '/outfits'
    | '/wardrobe'
    | '/wardrobe/item/$itemId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/instellingen'
    | '/wishlist'
    | '/outfits/$outfitsId'
    | '/outfits/nieuw'
    | '/wardrobe/toevoegen'
    | '/outfits'
    | '/wardrobe'
    | '/wardrobe/item/$itemId'
  id:
    | '__root__'
    | '/'
    | '/instellingen'
    | '/wishlist'
    | '/outfits/$outfitsId'
    | '/outfits/nieuw'
    | '/wardrobe/toevoegen'
    | '/outfits/'
    | '/wardrobe/'
    | '/wardrobe/item/$itemId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InstellingenRoute: typeof InstellingenRoute
  WishlistRoute: typeof WishlistRoute
  OutfitsOutfitsIdRoute: typeof OutfitsOutfitsIdRoute
  OutfitsNieuwRoute: typeof OutfitsNieuwRoute
  WardrobeToevoegenRoute: typeof WardrobeToevoegenRoute
  OutfitsIndexRoute: typeof OutfitsIndexRoute
  WardrobeIndexRoute: typeof WardrobeIndexRoute
  WardrobeItemItemIdRoute: typeof WardrobeItemItemIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instellingen': {
      id: '/instellingen'
      path: '/instellingen'
      fullPath: '/instellingen'
      preLoaderRoute: typeof InstellingenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wardrobe/': {
      id: '/wardrobe/'
      path: '/wardrobe'
      fullPath: '/wardrobe'
      preLoaderRoute: typeof WardrobeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outfits/': {
      id: '/outfits/'
      path: '/outfits'
      fullPath: '/outfits'
      preLoaderRoute: typeof OutfitsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wardrobe/toevoegen': {
      id: '/wardrobe/toevoegen'
      path: '/wardrobe/toevoegen'
      fullPath: '/wardrobe/toevoegen'
      preLoaderRoute: typeof WardrobeToevoegenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outfits/nieuw': {
      id: '/outfits/nieuw'
      path: '/outfits/nieuw'
      fullPath: '/outfits/nieuw'
      preLoaderRoute: typeof OutfitsNieuwRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outfits/$outfitsId': {
      id: '/outfits/$outfitsId'
      path: '/outfits/$outfitsId'
      fullPath: '/outfits/$outfitsId'
      preLoaderRoute: typeof OutfitsOutfitsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wardrobe/item/$itemId': {
      id: '/wardrobe/item/$itemId'
      path: '/wardrobe/item/$itemId'
      fullPath: '/wardrobe/item/$itemId'
      preLoaderRoute: typeof WardrobeItemItemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InstellingenRoute: InstellingenRoute,
  WishlistRoute: WishlistRoute,
  OutfitsOutfitsIdRoute: OutfitsOutfitsIdRoute,
  OutfitsNieuwRoute: OutfitsNieuwRoute,
  WardrobeToevoegenRoute: WardrobeToevoegenRoute,
  OutfitsIndexRoute: OutfitsIndexRoute,
  WardrobeIndexRoute: WardrobeIndexRoute,
  WardrobeItemItemIdRoute: WardrobeItemItemIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
